version: "3"

services:
  # frontendの設定
  frontend:
    container_name: learning-vue
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./frontend:/home/node/app:cached
      - frontend_node_modules:/home/node/app/node_modules
    ports:
      - "4444:4444"
    depends_on:
      - backend
    networks:
      - app-network
  # backendの設定
  backend:
    container_name: learning-node
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    tty: true
    environment:
      # nodemonでホットリロードを有効化するための設定
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/home/node/app:cached
      - backend_node_modules:/home/node/app/node_modules
    ports:
      - "5555:5555"
    networks:
      - app-network
      - supabase_network_backend
volumes:
  frontend_node_modules:
  backend_node_modules:
  db-store:

networks:
  app-network:
  supabase_network_backend:
    external: true
